# YML是一种文件格式，全称为YAML（YAML Ain't Markup Language），SpringBoot通常使用YML作为项目配置。
# 它是一种人类可读的、简洁明了的数据序列化格式。YAML文件格式通常用于配置文件、数据交换、消息传递和其他应用程序。
# 可以通过文本编辑器进行编辑，也可以通过程序进行解析。YML文件格式是一种以层级缩进的方式表示程序数据结构的格式。
# 在数据表示方面比XML等格式更加简洁清晰易读。YML文件格式通常以“.yml”为扩展名。


#web服务配置
server:
  #端口
  port: 9090

#Spring 配置
spring:
  #数据库配置
  datasource:
   url: jdbc:mysql://localhost:3306/db_dormitory?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
   username: local
   password: 713xiamen
   driver-class-name: com.mysql.cj.jdbc.Driver